name: Build and deploy
on:
  push:
    branches: [test-branch2]

jobs:

  echo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: echo "hello world!" 
  